# coding: utf-8

# flake8: noqa

"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from osis_attribution_sdk.api.application_api import ApplicationApi

# import ApiClient
from osis_attribution_sdk.api_client import ApiClient
from osis_attribution_sdk.configuration import Configuration
from osis_attribution_sdk.exceptions import OpenApiException
from osis_attribution_sdk.exceptions import ApiTypeError
from osis_attribution_sdk.exceptions import ApiValueError
from osis_attribution_sdk.exceptions import ApiKeyError
from osis_attribution_sdk.exceptions import ApiAttributeError
from osis_attribution_sdk.exceptions import ApiException
# import models into sdk package
from osis_attribution_sdk.models.application_course_calendar import ApplicationCourseCalendar
from osis_attribution_sdk.models.error import Error

