# flake8: noqa

"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.11.0"

# import ApiClient
from osis_attribution_sdk.api_client import ApiClient

# import Configuration
from osis_attribution_sdk.configuration import Configuration

# import exceptions
from osis_attribution_sdk.exceptions import OpenApiException
from osis_attribution_sdk.exceptions import ApiAttributeError
from osis_attribution_sdk.exceptions import ApiTypeError
from osis_attribution_sdk.exceptions import ApiValueError
from osis_attribution_sdk.exceptions import ApiKeyError
from osis_attribution_sdk.exceptions import ApiException
