# coding: utf-8

# flake8: noqa
"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from osis_attribution_sdk.models.application_course_calendar import ApplicationCourseCalendar
from osis_attribution_sdk.models.error import Error
