"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.application_update_command import ApplicationUpdateCommand


class TestApplicationUpdateCommand(unittest.TestCase):
    """ApplicationUpdateCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationUpdateCommand(self):
        """Test ApplicationUpdateCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationUpdateCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
