# coding: utf-8

"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from osis_attribution_sdk.application_api import ApplicationApi  # noqa: E501
from openapi_client.rest import ApiException


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = osis_attribution_sdk.application_api.ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applicationcoursescalendars_list(self):
        """Test case for applicationcoursescalendars_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
