"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.attribution_function_enum import AttributionFunctionEnum
from osis_attribution_sdk.model.attribution_links import AttributionLinks
globals()['AttributionFunctionEnum'] = AttributionFunctionEnum
globals()['AttributionLinks'] = AttributionLinks
from osis_attribution_sdk.model.attribution import Attribution


class TestAttribution(unittest.TestCase):
    """Attribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttribution(self):
        """Test Attribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Attribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
