"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.renew_attribution_about_to_expire_command import RenewAttributionAboutToExpireCommand


class TestRenewAttributionAboutToExpireCommand(unittest.TestCase):
    """RenewAttributionAboutToExpireCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenewAttributionAboutToExpireCommand(self):
        """Test RenewAttributionAboutToExpireCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RenewAttributionAboutToExpireCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
