"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.vacant_declaration_type_enum import VacantDeclarationTypeEnum


class TestVacantDeclarationTypeEnum(unittest.TestCase):
    """VacantDeclarationTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVacantDeclarationTypeEnum(self):
        """Test VacantDeclarationTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VacantDeclarationTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
