"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.10
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_attribution_sdk
from osis_attribution_sdk.api.attribution_api import AttributionApi  # noqa: E501


class TestAttributionApi(unittest.TestCase):
    """AttributionApi unit test stubs"""

    def setUp(self):
        self.api = AttributionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attributions_list(self):
        """Test case for attributions_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
