"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.21
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.attribution_links import AttributionLinks


class TestAttributionLinks(unittest.TestCase):
    """AttributionLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributionLinks(self):
        """Test AttributionLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributionLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
