"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.tutor_attribution import TutorAttribution
from osis_attribution_sdk.model.vacant_declaration_type_enum import VacantDeclarationTypeEnum
globals()['TutorAttribution'] = TutorAttribution
globals()['VacantDeclarationTypeEnum'] = VacantDeclarationTypeEnum
from osis_attribution_sdk.model.vacant_course import VacantCourse


class TestVacantCourse(unittest.TestCase):
    """VacantCourse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVacantCourse(self):
        """Test VacantCourse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VacantCourse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
