"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.vacant_course import VacantCourse
globals()['VacantCourse'] = VacantCourse
from osis_attribution_sdk.model.vacant_course_list import VacantCourseList


class TestVacantCourseList(unittest.TestCase):
    """VacantCourseList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVacantCourseList(self):
        """Test VacantCourseList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VacantCourseList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
