"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.20
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_attribution_sdk
from osis_attribution_sdk.api.application_api import ApplicationApi  # noqa: E501


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_application_create(self):
        """Test case for application_create

        """
        pass

    def test_application_delete(self):
        """Test case for application_delete

        """
        pass

    def test_application_list(self):
        """Test case for application_list

        """
        pass

    def test_application_update(self):
        """Test case for application_update

        """
        pass

    def test_applicationcoursescalendars_list(self):
        """Test case for applicationcoursescalendars_list

        """
        pass

    def test_applications_summary_send(self):
        """Test case for applications_summary_send

        """
        pass

    def test_attributionsabouttoexpire_list(self):
        """Test case for attributionsabouttoexpire_list

        """
        pass

    def test_attributionsabouttoexpire_renew(self):
        """Test case for attributionsabouttoexpire_renew

        """
        pass

    def test_my_charge_summary(self):
        """Test case for my_charge_summary

        """
        pass

    def test_vacantcourses_list(self):
        """Test case for vacantcourses_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
