"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.attribution_class_links import AttributionClassLinks


class TestAttributionClassLinks(unittest.TestCase):
    """AttributionClassLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributionClassLinks(self):
        """Test AttributionClassLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributionClassLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
