"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.20
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.my_charge_summary import MyChargeSummary
globals()['MyChargeSummary'] = MyChargeSummary
from osis_attribution_sdk.model.my_charge_summary_list import MyChargeSummaryList


class TestMyChargeSummaryList(unittest.TestCase):
    """MyChargeSummaryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMyChargeSummaryList(self):
        """Test MyChargeSummaryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MyChargeSummaryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
