# coding: utf-8

"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.application_course_calendar import ApplicationCourseCalendar  # noqa: E501
from openapi_client.rest import ApiException

class TestApplicationCourseCalendar(unittest.TestCase):
    """ApplicationCourseCalendar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApplicationCourseCalendar
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.application_course_calendar.ApplicationCourseCalendar()  # noqa: E501
        if include_optional :
            return ApplicationCourseCalendar(
                title = 'Candidature aux cours vacants', 
                start_date = 'Mon Feb 15 00:00:00 GMT 2021', 
                end_date = 'Sun Feb 28 00:00:00 GMT 2021', 
                authorized_target_year = 2022, 
                is_open = True
            )
        else :
            return ApplicationCourseCalendar(
        )

    def testApplicationCourseCalendar(self):
        """Test ApplicationCourseCalendar"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
