"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.application_course_calendar import ApplicationCourseCalendar


class TestApplicationCourseCalendar(unittest.TestCase):
    """ApplicationCourseCalendar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationCourseCalendar(self):
        """Test ApplicationCourseCalendar"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationCourseCalendar()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
