"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.attribution_function_enum import AttributionFunctionEnum
from osis_attribution_sdk.model.attribution_links import AttributionLinks
from osis_attribution_sdk.model.effective_class_repartition import EffectiveClassRepartition
from osis_attribution_sdk.model.learning_unit_type_enum import LearningUnitTypeEnum
globals()['AttributionFunctionEnum'] = AttributionFunctionEnum
globals()['AttributionLinks'] = AttributionLinks
globals()['EffectiveClassRepartition'] = EffectiveClassRepartition
globals()['LearningUnitTypeEnum'] = LearningUnitTypeEnum
from osis_attribution_sdk.model.attribution import Attribution


class TestAttribution(unittest.TestCase):
    """Attribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttribution(self):
        """Test Attribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Attribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
