"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.attribution_about_to_expire import AttributionAboutToExpire
globals()['AttributionAboutToExpire'] = AttributionAboutToExpire
from osis_attribution_sdk.model.attribution_about_to_expire_list import AttributionAboutToExpireList


class TestAttributionAboutToExpireList(unittest.TestCase):
    """AttributionAboutToExpireList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributionAboutToExpireList(self):
        """Test AttributionAboutToExpireList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributionAboutToExpireList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
