"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.21
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_attribution_sdk.model.application_configuration_links import ApplicationConfigurationLinks


class TestApplicationConfigurationLinks(unittest.TestCase):
    """ApplicationConfigurationLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationConfigurationLinks(self):
        """Test ApplicationConfigurationLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationConfigurationLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
