"""
    Attribution Service

    A set of API endpoints that allow you to get information about attribution  # noqa: E501

    The version of the OpenAPI document: 1.20
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_attribution_sdk
from osis_attribution_sdk.model.attribution_function_enum import AttributionFunctionEnum
globals()['AttributionFunctionEnum'] = AttributionFunctionEnum
from osis_attribution_sdk.model.tutor_attribution import TutorAttribution


class TestTutorAttribution(unittest.TestCase):
    """TutorAttribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTutorAttribution(self):
        """Test TutorAttribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TutorAttribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
